### ISSUE TITLE
AttributeError: 'int' object has no attribute 'writerow'

### ISSUE THREAD

**Issue by M0he** [jiangph1001/flow-feature#2]
Process flowProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/root/rat/flow-feature/flow.py", line 36, in run
    self.read_pcap(pcap_name,self.writer)
  File "/root/rat/flow-feature/flow.py", line 317, in get_flow_feature_from_pcap
    writer.writerow(feature)
AttributeError: 'int' object has no attribute 'writerow'

出现如上问题，我使用异常捕获显示如上，为什么写不进去表格里面，特征是可以正常打印的

**Comment by jiangph1001** [comment]
emmm，看起来被错误传递了一个int类型进去
